@uri = http://localhost:5246
@id = 1
###
GET {{uri}}/users

###
GET {{uri}}/users/{{id}}

###
GET {{uri}}/users/{{id}}/videos

###

POST {{uri}}/users
Content-Type: application/json

{
    "name": "khan",
    "email": "khan@example.com"
}

###
POST {{uri}}/videos
Content-Type: application/json

{
   "title": "ctoza7332437",
   "description": "wt434324h77",
   "userId": 2
}

###
GET {{uri}}/videos/
